# Generated by Django 4.2.1 on 2023-05-25 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id_I', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=50)),
                ('num_people', models.IntegerField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'ItemLocation',
            },
        ),
        migrations.CreateModel(
            name='UserP',
            fields=[
                ('id_U', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('phone', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('Privet', 'privet'), ('Public', 'public')], max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserP',
            },
        ),
    ]
