# Generated by Django 4.2.1 on 2023-05-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_User', models.IntegerField(blank=True, null=True, unique=True)),
                ('id_Place', models.IntegerField(blank=True, null=True, unique=True)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'Renters',
            },
        ),
    ]
