# Generated by Django 4.2.1 on 2023-05-27 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_renters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlocation',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='places_app.userp'),
        ),
    ]
